services:
  - type: web
    name: akilacard
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn Akilacard.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Akilacard.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: PYTHON_VERSION
        value: 3.13

    staticPublishPath: staticfiles
    autoDeploy: true
